### ISSUE TITLE
Process RCS messages

### ISSUE THREAD

**Issue by k9protection** [capcom6/android-sms-gateway#100]
Firstly, I don't know the feasibility of this and don't expect it.. But with Google now pushing their default app to use RCS messages as standard, it would be nice if the software could parse these messages in the same way as an SMS (even if it strips rich content and only sends through the text element.

This is very much a nice to have and not essential. We've been in production with this as our SMS server for the last 24 hours and so far it's working very efficiently. Bravo for an excellent project.

**Comment by capcom6** [comment]
Hello.

There are significant challenges with implementing RCS, primarily because RCS is a protocol description with multiple implementations. Unlike SMS, Google does not provide a simple API for RCS that third-party apps can use. As it stands, Google's implementation is similar to iMessage on iOS, meaning there is no straightforward way to integrate it into third-party applications.

Additionally, not all carriers support RCS, and there are compatibility issues even among those that do support it.

While I will keep this feature in mind, there are currently no plans to implement it.

See also [Google Support Thread](https://support.google.com/messages/thread/247624435/when-will-rcs-api-be-released-to-third-party-developers?hl=en).

**Comment by k9protection** [comment]
Makes perfect sense - thank you for the update. I'm sure in time they'll streamline it and it will become more straightforward.. (I have more faith in Google than Apple for that). The reason for asking was it initially threw me when messages from some devices weren't being received by the gateway and parsed in to our software - soon found the issue and disabled RCS from within the phone being used as a gateway and clients now know to communicate with it as SMS.

It may be worth a mention here for anyone else that runs in to this problem.. After we'd turned off RCS on the gateway device, an iPhone we tested failed to realise not to communicate via RCS, and the only way we cured it was by sending a text to it from the gateway phone, which seemed to force a refresh)
