### ISSUE TITLE
INTERNAL PROBLEM WITH SMS-GATEWAY CAPCOM6

### ISSUE THREAD

**Issue by Gagan7979** [capcom6/android-sms-gateway#108]
C:\Windows\System32>curl -X POST -u <sms>:<pliTzgVF> \
The system cannot find the file specified.

C:\Windows\System32>  -H "Content-Type: application/json" \
'-H' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32>  -d '{ "message": "Hello, world!", "phoneNumbers": ["+79990001234", "+79995556677"] }' \
'-d' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32>  http://<10.0.0.85>:8080/message
The system cannot find the file specified.

hey i am receiving this error when i run cmd with curl.i am on windows 11 and using moto g pure android phone with one sim card. please help me in fixing this issue to send sms.i have already run CHKDSK cmd everything is good in pc. Just problem with this message please check

**Comment by capcom6** [comment]
It looks like there are a few problems with the way the `curl` command is being used in the Windows Command Prompt. The errors are due to syntax issues and incorrect usage of the `curl` command.

Here's a corrected version of the `curl` command you should use:

```cmd
curl -X POST -u "<username>:<password>" -H "Content-Type: application/json" -d "{ \"message\": \"Hello, world!\", \"phoneNumbers\": [\"+79990001234\", \"+79995556677\"] }" http://10.0.0.85:8080/message
```

Please replace `<username>` and `<password>` with the actual username and password for authentication.

To break it down:
1. The entire `curl` command should be written on a single line.
2. The `-u` option is used for authentication. Replace `<username>` and `<password>` with your credentials.
3. The `-H` option specifies the header. In this case, it sets the `Content-Type` to `application/json`.
4. The `-d` option specifies the data to be sent in the POST request. The data should be in JSON format and properly escaped.
5. Finally, the URL `http://10.0.0.85:8080/message` should be the endpoint you're sending the request to.

**Comment by Gagan7979** [comment]
now it says invalid token 0x80090308

**Comment by Gagan7979** [comment]
i will really appreciate if u can book a call with me i am working on this
problem from two days
didnot sleep from 30hours still getting error please
+14374247963

**Comment by Gagan7979** [comment]
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_INVALID_TOKEN (0x80090308) - The token supplied to the function is invalid

am getting this message now i will really appreciate if you can please make me a call am working from last 2 days to fix it and use sms gateway +14374247963 or please find a solution

**Comment by capcom6** [comment]
Unfortunately, this issue is not related to the project. It is an issue with using `curl` on Windows. I recommend using Linux or Mac, because all examples are tested on these OSes. Regarding the last error, please check that you are using `http` for the local server, not `https`. Alternatively, try using a cloud server as described in https://sms.capcom.me/getting-started/public-cloud-server/

Sorry, but because this is an open-source project, I don't provide any phone support.

**Comment by KleKlai** [comment]
@Gagan7979 try to send request via POSTMAN its a great tool.

**Comment by Gagan7979** [comment]
can you send me link along with instructions
and which gateway i have to use on android phns

**Comment by capcom6** [comment]
Hello!

Do you have any other questions regarding the project itself, not the third-party tools like curl or Postman?

**Comment by Gagan7979** [comment]
can you please figure out am getting this message and then i debug with adb
shell still getting same error please need help asap
(also i get notification while sending -saying sms gateway is tryring yo
send large sum message allow or deny ) i allow it it sends 30-40
notifications till i allow ) it fails when i check

**Comment by capcom6** [comment]
The Android operating system has built-in limits for sending messages. This could be the reason for the error you're experiencing.

For troubleshooting steps and recommendations regarding this error, please refer to our FAQ page:
https://sms-gate.app/faq/errors/#result_error_limit_exceeded-error
