### ISSUE TITLE
Can't send numbers in message

### ISSUE THREAD

**Issue by RahulRimal** [capcom6/android-sms-gateway#142]
Whenever i try to send numeric characters in message like message: "test 123" i get RESULT_ERROR_GENERIC_FAILURE. SMS gets sent normally if i remove the numeric characters but with numeric characters, it gets failed

**Comment by capcom6** [comment]
Hello!

Please provide the following information:

1. App Version: [e.g., 1.16.0]
2. Mode: [Local, Cloud, or Private]
3. Device: [e.g., Google Pixel]
4. OS: [e.g., Android 11]
5. Integration: [e.g., CLI, API, SDK, etc.]

Additionally, please share an example of the code or API request you used to send the message.

The app internally uses UTF-8 encoding for messages, which supports almost all characters, including emojis and national symbols. Given this, the problem might be related to incorrect encoding in the original request. 

To help troubleshoot:
1. Can you confirm if the message with numbers appears correctly in the Messages tab of the app? Please, provide a screenshot.
2. Have you tried sending the same message using the device's default messaging app? If so, what was the result?

This information will help me identify the root cause of the issue and provide a solution.
