### ISSUE TITLE
Question. Energy saving by app

### ISSUE THREAD

**Issue by misiek75** [capcom6/android-sms-gateway#17]
Does the application on android need to have power saving mode turned off to run through interruptions ?

**Comment by capcom6** [comment]
The application operates differently depending on whether you're using it in local mode or cloud mode.

In local mode, the application utilizes a foreground service with a wake lock. This means there's no need to adjust your power saving settings. However, please be aware that this could cause your battery to drain more quickly.

In cloud mode, the app uses Firebase Cloud Messaging (FCM) for push notifications. Again, there's no need to adjust your power saving settings. However, you might experience delays between sending an API request to the cloud server and the device sending an SMS, especially when the device is in deep sleep mode. I suspect this might be improved by adjusting the priority of FCM messages. I'll investigate this further and provide you with an update later.

I recommend testing the application with and without power saving mode to understand how it performs under your specific conditions because the behavior can vary depending on the specific device manufacturer and the version of Android you are using.

**Comment by capcom6** [comment]
Hello!

I just wanted to provide a bit more insight into how our app operates in cloud mode.

I've tweaked the priority settings for our Firebase Cloud Messaging (FCM) messages, which means they should now get delivered even when your device is in power-saving modes like Doze. However, take note that there's a limit to the rate of high-priority messages. Therefore, I'd strongly suggest running some tests on your device under different conditions and consider disabling the power-saving mode for the app if you encounter any issues.

Alternatively, you could run the local server alongside the cloud server connection. This should keep your device awake and responsive.

Here are a few links if you're interested in diving into the technical details:

* [Android Power Management Details](https://developer.android.com/topic/performance/power/power-details)
* [FCM Message Priority](https://firebase.google.com/docs/cloud-messaging/android/message-priority?hl=en)
* [Android Pie Power Management](https://developer.android.com/about/versions/pie/power)

Feel free to reach out if you have any more questions, or if there's anything else I can help you with!

Thanks for your question!
