### ISSUE TITLE
Error on phone number

### ISSUE THREAD

**Issue by WesleyMarinho** [capcom6/android-sms-gateway#24]
Hello, trying to make shipments using the cload service but it always tells me that the number is wrong... but I already checked and it is correct.

usage +55 = Country code
and the rest of the phone
![0d65dc1e-3521-4d5c-a3f4-aa3615fa7328](https://github.com/capcom6/android-sms-gateway/assets/69599093/1e9484f7-94f3-4a10-b2a0-051fd32d055c)

**Comment by capcom6** [comment]
Hello!

Could you please provide the full text of the error message? You can check the status of the message by making a [GET /message/{id} request](https://capcom6.github.io/android-sms-gateway/#/Messages/get-message-id).

From the logs, it appears that you attempted to use SIM cards №2 and №3, which do not exist in your phone. Additionally, when using SIM card №1, you encountered a system error [RESULT_RIL_MODEM_ERR](https://developer.android.com/reference/android/telephony/SmsManager#RESULT_RIL_MODEM_ERR), which is beyond the scope of the app.

I recommend trying to send a message with the standard messaging app on your device, and then by API without specifying the SIM number in the request. This might help if the issue lies in SIM selection.

**Comment by WesleyMarinho** [comment]
![image](https://github.com/capcom6/android-sms-gateway/assets/69599093/e11bd998-0450-4cec-9bfb-6fcdd1e4f4f5)
