### ISSUE TITLE
Formatting sms message

### ISSUE THREAD

**Issue by fabio323ti** [capcom6/android-sms-gateway#62]
Hi, i'm try to format sms messages but any choice was in error.

for example 👍 

'message' => 'Hi,' .  'This is the message', (the only work)

'message' => 'Hi,' .  \n 'This is the message', (error)

'message' => 'Hi,' .  '\n'.  'This is the message', (error)

some way to brake line in message?

thanks

**Comment by capcom6** [comment]
Hello,

Thank you for reaching out. There are no limitations on the characters you can use in the message field from the app's side.

To assist you better, could you please provide some additional details?

- What error message are you encountering?
- Are you utilizing PHP for this? If so, have you tried using our PHP client library available at https://github.com/capcom6/android-sms-gateway-php?

Regarding your code snippets, the second example has a syntax error because `\n` should be within quotes when being concatenated with the `.` operator.

The third example is syntactically correct, but the single quotes will not interpret `\n` as a newline character. In PHP, you need to use double quotes for escape sequences like newline characters to be recognized. You can also use the `PHP_EOL` constant, which is the correct 'End Of Line' symbol for the platform PHP is running on. You can read more about these differences on PHP's official documentation: https://www.php.net/manual/en/language.types.string.php

Here's how you could format the message with a newline:

```php
'message' => "Hi,\nThis is the message",
```

Or using `PHP_EOL`:

```php
'message' => "Hi," . PHP_EOL . "This is the message",
```

Please try the above solutions, and if you're still experiencing issues, let me know the exact error message, and I'll be happy to help further.

**Comment by fabio323ti** [comment]
i'd solved formatting text inside var using shift+return on keyboards..

'message' => "Hi,
this is the message on line1
this is the message on line 2
',
