### ISSUE TITLE
Username /Password in public gateway?

### ISSUE THREAD

**Issue by faiz106** [capcom6/android-sms-gateway#78]
I have setup my server and its up and running . now problem is when i hit POST request on postman then it asks for username /Password because without this it. gives 401 unauthorized error .
![Screenshot 2024-06-21 at 12 11 21 PM](https://github.com/capcom6/android-sms-gateway/assets/1450709/8304010e-4d57-4940-88de-5b5837e3d702)

**Comment by capcom6** [comment]
Hello!

The credentials are shown on the Home screen of the app under the 'Cloud server' section, just as in the screenshot you've provided.

Please ensure you've correctly set both the private server address with the full path and the private token in the app, as described in the https://sms.capcom.me/getting-started/private-server/#configure-the-android-app. After updating these settings, remember to restart the app on your device for the changes to take effect.

**Comment by faiz106** [comment]
I am using my own server.

so it will be called as public gateway correct?

so i have set public gateway in the app like this : http://99.99.999.999/

and also made this in settings as well with same : http://99.99.999.999/

but still no username/password shown up..

what could be missing ?

i also did firebase setup

**Comment by capcom6** [comment]
The term "Cloud server" just refers to using a remote server, as opposed to a local server.

Could you please confirm the value of `gateway.mode` in your `config.yml`? Which instructions did you follow to set up the server: [Private Server](https://sms.capcom.me/getting-started/private-server/) or [Custom Gateway](https://sms.capcom.me/getting-started/custom-gateway/)?

When you mention "I have set public gateway in the app," are you referring to rebuilding the APK with altered source code, or just updating the "API URL" in the app's settings? If you updated the settings, remember to use the full path, like `https://99.99.999.999/api/mobile/v1`.

Additionally, it's important to use HTTPS instead of HTTP. The app requires TLS to establish a connection to the server.

**Comment by faiz106** [comment]
THanks i did https work on server and then issue got resolved
