### ISSUE TITLE
Can We run own private server without docker?

### ISSUE THREAD

**Issue by musamasays** [capcom6/android-sms-gateway#86]
I am not able to run docker on my vps due to processor architecture. Is there any way to run without docker.

Any guidance will be appreciated

**Comment by capcom6** [comment]
Hello!

Yes, you can run your own private server without Docker, but you'll need to manually compile the backend directly on your VPS or use cross-compilation.

**Prerequisites:**
1. Go 1.22 or higher.
2. Internet access to download dependencies.

**Steps:**
1. Clone the repository.
2. Build the project using `go build -o path/to/output/binary ./cmd/sms-gateway`. For cross-compilation, set the `GOOS` and `GOARCH` environment variables accordingly. For example: `GOOS=linux GOARCH=arm64 go build -o path/to/output/binary ./cmd/sms-gateway`. You can find available combinations [here](https://pkg.go.dev/internal/platform).
3. You're all set. Follow the instructions for setting up a Private server, but instead of using Docker, utilize the built binary directly. You might also need to create a systemd unit file to run the backend as a service.

**Comment by capcom6** [comment]
Hello, @musamasays 

Do you have any more questions or need further assistance? If not, may I proceed to close this issue?
