### ISSUE TITLE
WifiLock

### ISSUE THREAD

**Issue by domcars0** [capcom6/android-sms-gateway#99]
**Is your feature request related to a problem? Please describe.**
When using this app on a tablet (or phone) on which the screen switch off after a certain delay, the WiFi is also switch off. So it's not possible to contact the local server anymore :-(

**Describe the solution you'd like**
I think it's possible to use the WiFiLock method in the code to keep WiFi on even when the screen turn off.

**Comment by capcom6** [comment]
Hello!

The app already uses `WiFiLock`, but it doesn't work on Android versions since 14 and on some vendor-customized firmwares. Please see https://github.com/capcom6/android-sms-gateway/issues/90; it might be related to your case.

Also, please check for any power-saving options on your phone, as they can vary by vendor.

The recommended solution is to use a Cloud/Private server.

**Comment by domcars0** [comment]
Hi capcom6, 
Thank you for your answer. You're right, my problem did'nt come from sms-gateway but from my wifi repeater which reject clients sometime. After changing it all is ok. Thank you very much again and sorry to have bothered you. And thanks also for your work on sms-gateway.
